security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                # redirect unauthenticated visitors to login_path
                login_path: dashboard_login
                check_path: dashboard_login
                enable_csrf: true
            logout:
                path: dashboard_logout

    # Only test and login routes are public
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/test, roles: PUBLIC_ACCESS}
        - { path: ^/, roles: ROLE_ADMIN}

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
